### ISSUE TITLE
Bathroom cleaning guide 

### ISSUE THREAD

**Issue by SamHoffer** [Taskbird/community-content#19]
### Follow [Blog Guidelines](https://github.com/Taskbird/community-content/blob/76087ede06901ab5b395ed4cf776a4b217335f4d/Guest%20Blog%20Writing%20TB%20Mid_.pdf)

Comment bellow if you want to create a blog article or a video for this topic! 

When you submit your final draft send your file to community@taskbird.com

**Comment by ninjaclean** [comment]
Hi, I'd like to write on this topic. What are my next steps?

**Comment by SamHoffer** [comment]
@ninjaclean thank you for expressing you interest in this topic! Please submit an outline of your ideas for this topic. After we review it you can begin working on your final draft. Make sure to follow our blog guidelines. You can email any further work to community@taskbird.com or reach out on our forum.

**Comment by ninjaclean** [comment]
Hi Sam Hoffer,
I would like to send you an outline for my article on cleaning bathrooms. I’m working on that now but wanted to explore the idea of expanding this bathroom cleaning section to include a variety of articles. Please advise if I should go ahead and prepare outlines for each bathroom cleaning approach listed below.
I would like to do three or four separate articles on this subject because there are several different types of bathroom cleaning projects, each of which require different treatments. I will toss out several different article headlines below so you can see what I mean. 
If you would prefer that I write only one article per area – please let me know soon as possible. 

Potential Headlines
1)	Best Private Residence Bathroom Cleaning Methods
2)	Disaster Bathroom Approaches (incl for the uber busy multi-child household, teen bathroom disasters, multi-user bathroom cleaning (Airbnb, rooming house, etc.)
3)	Industrial Bathroom Cleaning
4)	Allergy-Free Bathroom Cleaning Method

**Comment by SamHoffer** [comment]
@ninjaclean, these are all really great ideas for this topic! One longer blog that covers these subjects would be more suitable as apposed to several different/shorter articles, however. If you want to create a blog that includes all of these ideas or even just a couple that would be a great start. 

Additionally, we do accept videos that cover the same genre of topics if that seems like something you would be interested in. Thank you so much for your time and efforts thus far, looking forward to reading more of your ideas.

**Comment by Mr254Kenya** [comment]
@SamHoffer I'm not sure if the topic is already being handled since I see interest from a fellow content creator. But, if it is not being handled, I request the opportunity to tackle it. Attached is a general outline of how I wish to approach the task. Of course, you can point out anything that may need to be added. Regards
[General Outline_ Bathroom Cleaning Guide #19.docx](https://github.com/Taskbird/community-content/files/7655365/General.Outline_.Bathroom.Cleaning.Guide.19.docx)
.

**Comment by SamHoffer** [comment]
@Mr254Kenya I am going to give the other writer on this topic a few more days to submit this piece due to them claiming it first. However, I will notify you if we are able to assign this piece to you instead if there are no further submissions. This will show up as a "closed issue" for the time being. Thank you for your understanding.
